version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports: 
      - "3001:3001"
      - "9229:9229"
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
  selenium-tests:
    build:
      context: ./selenium_tests
      dockerfile: ./Dockerfile
    command: pytest ./src/test_node_sample.py
    depends_on:
      - chrome
      - server
      - client
    profiles:
      - tests
  chrome:
    image: selenium/standalone-chrome-debug
    hostname: chrome
    ports:
      - "4444:4444"
      - "5900:5900"
